module.exports =
{
    CONNECTION_ADD: "CONNECTION_ADD",
    CONFIG_CONNECTION_SAVE: "CONFIG_CONNECTION_SAVE",
    CONNECTION_CONNECTED: "CONNECTION_CONNECTED",
    CONNECTION_DISCONNECTED: "CONNECTION_DISCONNECTED",
    CONNECTION_REFUSED: "CONNECTION_REFUSED"
};