module.exports =
{
    CONNECTION_ADD: "CONNECTION_ADD",
    CONNECTION_UPDATE: "CONNECTION_UPDATE",
    CONNECTION_REMOVE: "CONNECTION_REMOVE",
    CONFIG_CONNECTION_SAVE: "CONFIG_CONNECTION_SAVE",
    CONNECTION_CONNECTED: "CONNECTION_CONNECTED",
    CONNECTION_DISCONNECTED: "CONNECTION_DISCONNECTED",
    CONNECTION_REFUSED: "CONNECTION_REFUSED",
    CONNECTION_UPDATE_FAILED: "CONNECTION_UPDATE_FAILED",
    GET_SETTINGS: "GET_SETTINGS",
    SET_SETTINGS: "SET_SETTINGS",
    UPDATE_BUTTON: "UPDATE_BUTTON",
    GET_MACRO_META_DATA: "GET_MACRO_META_DATA"
};